name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # use file .node-version to determine node version
          node-version-file: .node-version

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npm run ci:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
